update:
	./update_image.sh
	
qemu:	
	qemu-system-i386 -nographic  -serial mon:stdio  -fda floppy.img

# For -nographic just enter: 先按ctrl+A 然后松开，再按x或者c
# Ctrl-A X
# which means

# first press Ctrl + A (A is just key a, not the alt key),
# then release the keys,
# afterwards type X.